Repository 24-1-SKKU-SE/2024spring_42class_team12, pull requests merged in 2024-05, with the labels that each got.

#6 [Feat] jwt 토큰 발급 및 확인 구현
  FixSkkuBack/fixskku/build.gradle
  FixSkkuBack/fixskku/src/main/java/com/skku/fixskku/apipayload/GeneralExceptionHandler.java
  FixSkkuBack/fixskku/src/main/java/com/skku/fixskku/apipayload/ResponseApi.java
  FixSkkuBack/fixskku/src/main/java/com/skku/fixskku/apipayload/ResponseStatus.java
  FixSkkuBack/fixskku/src/main/java/com/skku/fixskku/apipayload/exception/GeneralException.java
  FixSkkuBack/fixskku/src/main/java/com/skku/fixskku/token/controller/TokenController.java
  FixSkkuBack/fixskku/src/main/java/com/skku/fixskku/token/service/TokenService.java
Labels: feat

#11 #5 [feat] 신고 기능 개발
  .github/ISSUE_TEMPLATE/issue-template.md
  .github/PULL_REQUEST_TEMPLATE.md
  FixSkkuBack/fixskku/build.gradle
  FixSkkuBack/fixskku/src/main/java/com/skku/fixskku/common/apipayload/GeneralExceptionHandler.java
  FixSkkuBack/fixskku/src/main/java/com/skku/fixskku/common/apipayload/ResponseApi.java
  FixSkkuBack/fixskku/src/main/java/com/skku/fixskku/common/apipayload/ResponseStatus.java
  FixSkkuBack/fixskku/src/main/java/com/skku/fixskku/common/apipayload/exception/GeneralException.java
  FixSkkuBack/fixskku/src/main/java/com/skku/fixskku/common/domain/BuildingType.java
  FixSkkuBack/fixskku/src/main/java/com/skku/fixskku/common/domain/CampusType.java
  FixSkkuBack/fixskku/src/main/java/com/skku/fixskku/common/domain/FacilityStatus.java
  FixSkkuBack/fixskku/src/main/java/com/skku/fixskku/common/domain/FacilityType.java
  FixSkkuBack/fixskku/src/main/java/com/skku/fixskku/common/domain/ReportStatus.java
  FixSkkuBack/fixskku/src/main/java/com/skku/fixskku/facility/controller/FacilityController.java
  FixSkkuBack/fixskku/src/main/java/com/skku/fixskku/facility/domain/Facility.java
  FixSkkuBack/fixskku/src/main/java/com/skku/fixskku/facility/dto/res/FacilityResDto.java
  FixSkkuBack/fixskku/src/main/java/com/skku/fixskku/facility/repository/FacilityRepository.java
  FixSkkuBack/fixskku/src/main/java/com/skku/fixskku/facility/service/FacilityService.java
  FixSkkuBack/fixskku/src/main/java/com/skku/fixskku/report/controller/ReportController.java
  FixSkkuBack/fixskku/src/main/java/com/skku/fixskku/report/domain/Report.java
  FixSkkuBack/fixskku/src/main/java/com/skku/fixskku/report/dto/req/ReportReqDto.java
  FixSkkuBack/fixskku/src/main/java/com/skku/fixskku/report/dto/res/ReportResDto.java
  FixSkkuBack/fixskku/src/main/java/com/skku/fixskku/report/repository/ReportRepository.java
  FixSkkuBack/fixskku/src/main/java/com/skku/fixskku/report/service/ReportService.java
  FixSkkuBack/fixskku/src/main/java/com/skku/fixskku/report/service/ReportServiceImpl.java
  FixSkkuBack/fixskku/src/main/java/com/skku/fixskku/token/controller/TokenController.java
  FixSkkuBack/fixskku/src/main/java/com/skku/fixskku/token/service/TokenService.java
  FixSkkuBack/fixskku/src/test/java/com/skku/fixskku/report/service/ReportServiceImplTest.java
Labels: feat, refactor

#12 #5, #10 [feat] 신고 기능 개발 및 코드 리팩토링
  .github/ISSUE_TEMPLATE/issue-template.md
  .github/PULL_REQUEST_TEMPLATE.md
  FixSkkuBack/fixskku/src/main/java/com/skku/fixskku/common/apipayload/GeneralExceptionHandler.java
  FixSkkuBack/fixskku/src/main/java/com/skku/fixskku/common/apipayload/ResponseApi.java
  FixSkkuBack/fixskku/src/main/java/com/skku/fixskku/common/apipayload/ResponseStatus.java
  FixSkkuBack/fixskku/src/main/java/com/skku/fixskku/common/apipayload/exception/GeneralException.java
  FixSkkuBack/fixskku/src/main/java/com/skku/fixskku/common/domain/BuildingType.java
  FixSkkuBack/fixskku/src/main/java/com/skku/fixskku/common/domain/CampusType.java
  FixSkkuBack/fixskku/src/main/java/com/skku/fixskku/common/domain/FacilityStatus.java
  FixSkkuBack/fixskku/src/main/java/com/skku/fixskku/common/domain/FacilityType.java
  FixSkkuBack/fixskku/src/main/java/com/skku/fixskku/common/domain/ReportStatus.java
  FixSkkuBack/fixskku/src/main/java/com/skku/fixskku/entity/Facility.java
  FixSkkuBack/fixskku/src/main/java/com/skku/fixskku/facility/controller/FacilityController.java
  FixSkkuBack/fixskku/src/main/java/com/skku/fixskku/facility/domain/Facility.java
  FixSkkuBack/fixskku/src/main/java/com/skku/fixskku/facility/dto/res/FacilityResDto.java
  FixSkkuBack/fixskku/src/main/java/com/skku/fixskku/facility/repository/FacilityRepository.java
  FixSkkuBack/fixskku/src/main/java/com/skku/fixskku/facility/service/FacilityService.java
  FixSkkuBack/fixskku/src/main/java/com/skku/fixskku/report/controller/ReportController.java
  FixSkkuBack/fixskku/src/main/java/com/skku/fixskku/report/domain/Report.java
  FixSkkuBack/fixskku/src/main/java/com/skku/fixskku/report/dto/req/ReportReqDto.java
  FixSkkuBack/fixskku/src/main/java/com/skku/fixskku/report/dto/res/ReportResDto.java
  FixSkkuBack/fixskku/src/main/java/com/skku/fixskku/report/repository/ReportRepository.java
  FixSkkuBack/fixskku/src/main/java/com/skku/fixskku/report/service/ReportService.java
  FixSkkuBack/fixskku/src/main/java/com/skku/fixskku/report/service/ReportServiceImpl.java
  FixSkkuBack/fixskku/src/main/java/com/skku/fixskku/token/service/TokenService.java
  FixSkkuBack/fixskku/src/test/java/com/skku/fixskku/report/service/ReportServiceImplTest.java
Labels: feat, refactor

#14 #13 [feat] 자신의 신고 조회 기능 개발
  FixSkkuBack/fixskku/src/main/java/com/skku/fixskku/common/apipayload/ResponseStatus.java
  FixSkkuBack/fixskku/src/main/java/com/skku/fixskku/report/controller/ReportController.java
  FixSkkuBack/fixskku/src/main/java/com/skku/fixskku/report/dto/res/ReportListResDto.java
  FixSkkuBack/fixskku/src/main/java/com/skku/fixskku/report/repository/ReportRepository.java
  FixSkkuBack/fixskku/src/main/java/com/skku/fixskku/report/service/ReportService.java
  FixSkkuBack/fixskku/src/main/java/com/skku/fixskku/report/service/ReportServiceImpl.java
Labels: feat

#17 #15 [feat] 자신의 신고 상세 조회 기능 개발
  FixSkkuBack/fixskku/src/main/java/com/skku/fixskku/report/controller/ReportController.java
  FixSkkuBack/fixskku/src/main/java/com/skku/fixskku/report/repository/ReportRepository.java
  FixSkkuBack/fixskku/src/main/java/com/skku/fixskku/report/service/ReportService.java
  FixSkkuBack/fixskku/src/main/java/com/skku/fixskku/report/service/ReportServiceImpl.java
Labels: feat

#19 #18 [feat] 챗봇 호출 및 결과 반환 기능 개발
  FixSkkuBack/fixskku/src/main/java/com/skku/fixskku/chatbot/constants/AnswerType.java
  FixSkkuBack/fixskku/src/main/java/com/skku/fixskku/chatbot/constants/ChatbotUrl.java
  FixSkkuBack/fixskku/src/main/java/com/skku/fixskku/chatbot/controller/ChatbotController.java
  FixSkkuBack/fixskku/src/main/java/com/skku/fixskku/chatbot/dto/req/ToChatbotReqDto.java
  FixSkkuBack/fixskku/src/main/java/com/skku/fixskku/chatbot/dto/res/ChatbotResDto.java
  FixSkkuBack/fixskku/src/main/java/com/skku/fixskku/chatbot/dto/res/FromChatbotResDataDto.java
  FixSkkuBack/fixskku/src/main/java/com/skku/fixskku/chatbot/dto/res/ToFrontResDto.java
  FixSkkuBack/fixskku/src/main/java/com/skku/fixskku/chatbot/service/ChatbotService.java
  FixSkkuBack/fixskku/src/main/java/com/skku/fixskku/chatbot/service/ChatbotServiceImpl.java
  FixSkkuBack/fixskku/src/main/java/com/skku/fixskku/common/apipayload/ResponseStatus.java
Labels: feat

#20 #18 [feat] 챗봇 호출 및 결과 반환 기능 개발
  FixSkkuBack/fixskku/src/main/java/com/skku/fixskku/chatbot/constants/AnswerType.java
  FixSkkuBack/fixskku/src/main/java/com/skku/fixskku/chatbot/constants/ChatbotUrl.java
  FixSkkuBack/fixskku/src/main/java/com/skku/fixskku/chatbot/controller/ChatbotController.java
  FixSkkuBack/fixskku/src/main/java/com/skku/fixskku/chatbot/dto/req/ToChatbotReqDto.java
  FixSkkuBack/fixskku/src/main/java/com/skku/fixskku/chatbot/dto/res/ChatbotResDto.java
  FixSkkuBack/fixskku/src/main/java/com/skku/fixskku/chatbot/dto/res/FromChatbotResDataDto.java
  FixSkkuBack/fixskku/src/main/java/com/skku/fixskku/chatbot/dto/res/ToFrontResDto.java
  FixSkkuBack/fixskku/src/main/java/com/skku/fixskku/chatbot/service/ChatbotService.java
  FixSkkuBack/fixskku/src/main/java/com/skku/fixskku/chatbot/service/ChatbotServiceImpl.java
  FixSkkuBack/fixskku/src/main/java/com/skku/fixskku/common/apipayload/ResponseStatus.java
Labels: feat

#25 [feat] 관리자 도메인 api 구현
  FixSkkuBack/fixskku/src/main/java/com/skku/fixskku/admin/controller/AdminController.java
  FixSkkuBack/fixskku/src/main/java/com/skku/fixskku/admin/dto/req/ReportUpdateDto.java
  FixSkkuBack/fixskku/src/main/java/com/skku/fixskku/admin/repository/AdminRepository.java
  FixSkkuBack/fixskku/src/main/java/com/skku/fixskku/admin/service/AdminService.java
  FixSkkuBack/fixskku/src/main/java/com/skku/fixskku/admin/service/AdminServiceImpl.java
  FixSkkuBack/fixskku/src/main/java/com/skku/fixskku/common/apipayload/ResponseStatus.java
  FixSkkuBack/fixskku/src/main/java/com/skku/fixskku/facility/domain/Facility.java
  FixSkkuBack/fixskku/src/main/java/com/skku/fixskku/report/domain/Report.java
Labels: feat

#26 #9 [Fix] 관리자 신고 조회 기능 쿼리스트링을 한글로 받도록 수정 + 시설물 현황 조회 변경
  FixSkkuBack/fixskku/src/main/java/com/skku/fixskku/admin/controller/AdminController.java
  FixSkkuBack/fixskku/src/main/java/com/skku/fixskku/admin/repository/AdminRepository.java
  FixSkkuBack/fixskku/src/main/java/com/skku/fixskku/admin/service/AdminServiceImpl.java
  FixSkkuBack/fixskku/src/main/java/com/skku/fixskku/common/apipayload/ResponseStatus.java
  FixSkkuBack/fixskku/src/main/java/com/skku/fixskku/common/domain/ReportStatus.java
  FixSkkuBack/fixskku/src/main/java/com/skku/fixskku/facility/repository/FacilityRepository.java
  FixSkkuBack/fixskku/src/main/java/com/skku/fixskku/facility/service/FacilityService.java
  FixSkkuBack/fixskku/src/main/java/com/skku/fixskku/report/dto/res/ReportListResDto.java
Labels: fix
